const translations = {
    es: {
        meta_title: "TONAH EL HOMBRE ORQUESTA",
        lbl_idioma: "IDIOMA",
        lbl_edition: "EL HOMBRE ORQUESTA",
        lbl_hero_title: "TONAH",
        alt_hero_img: "Tonah El Hombre Orquesta",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "CLIC PARA REPRODUCIR",
        btn_grandes_momentos: "GRANDES MOMENTOS",
        modal_grandes_momentos_title: "GRANDES MOMENTOS",
        modal_grandes_momentos_desc: "Toca una imagen para ampliarla y deslizarla",
        btn_cerrar: "Cerrar",
        btn_comparte_historia: "COMPARTE MI HISTORIA TE LO AGRADEZCO",
        lbl_producido_por: "PRODUCIDO POR \"TALENT CARD\"",
        btn_contactanos_card: "CONTÁCTANOS",
        lbl_conoceme: "CONÓCEME",
        lbl_biografia: "Biografía",
        lbl_nombre_label: "Nombre:",
        val_nombre: "Tonah",
        lbl_edad_label: "Proyecto:",
        val_edad: "Música Independiente Urbana",
        lbl_nacimiento_label: "Origen:",
        val_nacimiento: "Ciudad de México",
        lbl_nacionalidad_label: "Nacionalidad:",
        val_nacionalidad: "Mexicana",
        lbl_estatura_label: "Estilo:",
        val_estatura: "Rock & Roll / Clásicos / Covers",
        lbl_formacion_titulo: "Formación Artística",
        lbl_perfil_label: "Perfil:",
        val_perfil_text: "Músico callejero e independiente de alto rendimiento escénico.",
        lbl_desempeno_label: "Habilidad:",
        val_desempeno_text: "Coordinación simultánea de múltiples instrumentos y percusiones en vivo.",
        lbl_especialidad_titulo: "Especialidad",
        lbl_disciplina_label: "Instrumentación:",
        val_disciplina_text: "Ejecución simultánea de guitarra, batería, armónica y accesorios al mismo tiempo.",
        lbl_tecnica_label: "Propuesta:",
        val_tecnica_text: "Rescate del rock clásico, pop y géneros retro con arreglos acústicos y percusivos autogestionados.",
        lbl_logros_titulo: "Logros y Trayectoria",
        val_logro_1: "📌 Fenómeno viral en redes sociales y espacios públicos emblemáticos de la CDMX (como el Parque México en la Condesa).",
        val_logro_2: "🎸 Destacado intérprete capaz de dominar múltiples instrumentos de manera simultánea ante cientos de espectadores.",
        val_logro_3: "🌐 Sólida trayectoria independiente llevando la música urbana y el rock callejero a escenarios y plataformas digitales de gran alcance.",
        btn_regresar_menu: "REGRESAR AL MENÚ 🚀",
        btn_conoceme: "CONOCEME",
        btn_portafolio: "PORTAFOLIO DE IMAGENES",
        btn_poder_musica: "EL PODER DE LA MUSICA",
        btn_contacto: "CONTACTO",
        contact_title: "REDES SOCIALES",
        contact_contracting: "CONTRATACIONES 52 56 5482 8000",
        btn_whatsapp: "WHATSAPP",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_youtube: "YOUTUBE",
        qr_heading: "ESCANEA EL CÓDIGO QR",
        btn_share_qr: "COMPARTIR QR",
        meta_title: "Tonah El Hombre Orquesta",
        cat1_t: "BIOGRAFÍA",
        cat1_c: "Biografía y trayectoria artística de Tonah El Hombre Orquesta...",
        cat2_t: "PORTAFOLIO DE IMAGENES",
        cat2_c: "Todos los días ensayo, ajusto mi sistema de poleas y pedales y perfecciono cada detalle de mi show...",
        cat3_t: "EL PODER DE LA MUSICA",
        cat3_c: "Mi mayor fortaleza es la versatilidad combinada con la autenticidad...",
        lbl_mis_fortalezas: "México en el corazón",
        btn_tributo_tri: "Tributo al TRI",
        btn_junto_mar: "Junto al Mar",
        btn_con_gente: "Cantando en Paris",
        btn_cantando_beatles: "Cantando a The beatles",
        btn_video_historia: "ME PRESENTO",
        btn_ver_detalles: "VER DETALLES"
    },
    en: {
        meta_title: "TONAH THE ONE-MAN BAND",
        lbl_idioma: "LANGUAGE",
        lbl_edition: "THE ONE-MAN BAND",
        lbl_hero_title: "TONAH",
        alt_hero_img: "Tonah The One-Man Band",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "CLICK TO PLAY",
        btn_grandes_momentos: "GREAT MOMENTS",
        modal_grandes_momentos_title: "GREAT MOMENTS",
        modal_grandes_momentos_desc: "Tap an image to zoom and swipe",
        btn_cerrar: "Close",
        btn_comparte_historia: "SHARE MY STORY, I APPRECIATE IT",
        lbl_producido_por: "PRODUCED BY \"TALENT CARD\"",
        btn_contactanos_card: "CONTACT US",
        lbl_conoceme: "ABOUT ME",
        lbl_biografia: "Biography",
        lbl_nombre_label: "Name:",
        val_nombre: "Tonah",
        lbl_edad_label: "Project:",
        val_edad: "Independent Urban Music",
        lbl_nacimiento_label: "Origin:",
        val_nacimiento: "Mexico City",
        lbl_nacionalidad_label: "Nationality:",
        val_nacionalidad: "Mexican",
        lbl_estatura_label: "Style:",
        val_estatura: "Rock & Roll / Classics / Covers",
        lbl_formacion_titulo: "Artistic Background",
        lbl_perfil_label: "Profile:",
        val_perfil_text: "High-performance street and independent musician.",
        lbl_desempeno_label: "Skill:",
        val_desempeno_text: "Simultaneous live coordination of multiple instruments and percussions.",
        lbl_especialidad_titulo: "Specialty",
        lbl_disciplina_label: "Instrumentation:",
        val_disciplina_text: "Simultaneous execution of guitar, drums, harmonica, and accessories at the same time.",
        lbl_tecnica_label: "Proposal:",
        val_tecnica_text: "Revival of classic rock, pop, and retro genres with self-managed acoustic and percussion arrangements.",
        lbl_logros_titulo: "Achievements & Track Record",
        val_logro_1: "📌 Viral phenomenon on social media and iconic public spaces in CDMX (such as Parque México in Condesa).",
        val_logro_2: "🎸 Outstanding performer capable of mastering multiple instruments simultaneously in front of hundreds of spectators.",
        val_logro_3: "🌐 Solid independent career bringing urban music and street rock to high-reach stages and digital platforms.",
        btn_regresar_menu: "BACK TO MENU 🚀",
        btn_conoceme: "ABOUT ME",
        btn_portafolio: "IMAGE PORTFOLIO",
        btn_poder_musica: "THE POWER OF MUSIC",
        btn_contacto: "CONTACT",
        contact_title: "SOCIAL MEDIA",
        contact_contracting: "BOOKINGS 52 56 5482 8000",
        btn_whatsapp: "WHATSAPP",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_youtube: "YOUTUBE",
        qr_heading: "SCAN THE QR CODE",
        btn_share_qr: "SHARE QR",
        meta_title: "Tonah The One-Man Band",
        cat1_t: "BIOGRAPHY",
        cat1_c: "Biography and artistic career of Tonah The One-Man Band...",
        cat2_t: "IMAGE PORTFOLIO",
        cat2_c: "Every day I rehearse, adjust my pulley and pedal system, and perfect every detail of my show...",
        cat3_t: "THE POWER OF MUSIC",
        cat3_c: "My greatest strength is versatility combined with authenticity...",
        lbl_mis_fortalezas: "Mexico in the heart",
        btn_tributo_tri: "Tribute to TRI",
        btn_junto_mar: "By the Sea",
        btn_con_gente: "Singing in Paris",
        btn_cantando_beatles: "Singing The Beatles",
        btn_video_historia: "LET ME INTRODUCE MYSELF",
        btn_ver_detalles: "VIEW DETAILS"
    },
    pt: {
        meta_title: "TONAH O HOMEM BANDA",
        lbl_idioma: "IDIOMA",
        lbl_edition: "O HOMEM BANDA",
        lbl_hero_title: "TONAH",
        alt_hero_img: "Tonah O Homem Banda",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "CLIQUE PARA REPRODUZIR",
        btn_grandes_momentos: "GRANDES MOMENTOS",
        modal_grandes_momentos_title: "GRANDES MOMENTOS",
        modal_grandes_momentos_desc: "Toque em uma imagem para ampliar e deslizar",
        btn_cerrar: "Fechar",
        btn_comparte_historia: "COMPARTILHE MINHA HISTÓRIA, EU AGRADEÇO",
        lbl_producido_por: "PRODUZIDO POR \"TALENT CARD\"",
        btn_contactanos_card: "CONTATE-NOS",
        lbl_conoceme: "QUEM SOU EU",
        lbl_biografia: "Biografia",
        lbl_nombre_label: "Nome:",
        val_nombre: "Tonah",
        lbl_edad_label: "Projeto:",
        val_edad: "Música Urbana Independente",
        lbl_nacimiento_label: "Origem:",
        val_nacimiento: "Cidade do México",
        lbl_nacionalidad_label: "Nacionalidade:",
        val_nacionalidad: "Mexicana",
        lbl_estatura_label: "Estilo:",
        val_estatura: "Rock & Roll / Clássicos / Covers",
        lbl_formacion_titulo: "Formação Artística",
        lbl_perfil_label: "Perfil:",
        val_perfil_text: "Músico de rua e independente de alto rendimento cênico.",
        lbl_desempeno_label: "Habilidade:",
        val_desempeno_text: "Coordenação simultânea de múltiplos instrumentos e percussões ao vivo.",
        lbl_especialidad_titulo: "Especialidade",
        lbl_disciplina_label: "Instrumentação:",
        val_disciplina_text: "Execução simultânea de guitarra, bateria, gaita e acessórios ao mesmo tempo.",
        lbl_tecnica_label: "Proposta:",
        val_tecnica_text: "Resgate do rock clássico, pop e gêneros retrô com arranjos acústicos e percussivos autogeridos.",
        lbl_logros_titulo: "Conquistas e Trajetória",
        val_logro_1: "📌 Fenômeno viral nas redes sociais e espaços públicos emblemáticos da Cidade do México (como o Parque México na Condesa).",
        val_logro_2: "🎸 Intérprete talentoso capaz de dominar vários instrumentos simultaneamente diante de centenas de espectadores.",
        val_logro_3: "🌐 Sólida trajetória independente levando a música urbana e o rock de rua a palcos e plataformas digitais de grande alcance.",
        btn_regresar_menu: "VOLTAR AO MENU 🚀",
        btn_conoceme: "QUEM SOU EU",
        btn_portafolio: "PORTFÓLIO DE IMAGENS",
        btn_poder_musica: "O PODER DA MÚSICA",
        btn_contacto: "CONTATO",
        contact_title: "REDES SOCIAIS",
        contact_contracting: "CONTRATAÇÕES 52 56 5482 8000",
        btn_whatsapp: "WHATSAPP",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_youtube: "YOUTUBE",
        qr_heading: "ESCANEIE O CÓDIGO QR",
        btn_share_qr: "COMPARTILHAR QR",
        meta_title: "Tonah O Homem Orquestra",
        cat1_t: "BIOGRAFIA",
        cat1_c: "Biografia e trajetória artística de Tonah O Homem Orquestra...",
        cat2_t: "PORTFÓLIO DE IMAGENS",
        cat2_c: "Todos os dias ensaio, ajusto meu sistema de polias e pedais e aperfeiçoo cada detalhe do meu show...",
        cat3_t: "O PODER DA MÚSICA",
        cat3_c: "Minha maior força é a versatilidade combinada com a autenticidade...",
        lbl_mis_fortalezas: "México no coração",
        btn_tributo_tri: "Tributo ao TRI",
        btn_junto_mar: "Junto ao Mar",
        btn_con_gente: "Cantando em Paris",
        btn_cantando_beatles: "Cantando The Beatles",
        btn_video_historia: "ME APRESENTO",
        btn_ver_detalles: "VER DETALHES"
    },
    fr: {
        meta_title: "TONAH L'HOMME ORCHESTRE",
        lbl_idioma: "LANGUE",
        lbl_edition: "L'HOMME ORCHESTRE",
        lbl_hero_title: "TONAH",
        alt_hero_img: "Tonah L'homme orchestre",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "CLIQUEZ POUR LIRE",
        btn_grandes_momentos: "GRANDS MOMENTS",
        modal_grandes_momentos_title: "GRANDS MOMENTOS",
        modal_grandes_momentos_desc: "Touchez une image pour l'agrandir et balayer",
        btn_cerrar: "Fermer",
        btn_comparte_historia: "PARTAGEZ MON HISTOIRE, JE VOUS REMERCIE",
        lbl_producido_por: "PRODUIT PAR \"TALENT CARD\"",
        btn_contactanos_card: "CONTACTEZ-NOUS",
        lbl_conoceme: "À PROPOS",
        lbl_biografia: "Biographie",
        lbl_nombre_label: "Nom :",
        val_nombre: "Tonah",
        lbl_edad_label: "Projet :",
        val_edad: "Musique Urbaine Indépendante",
        lbl_nacimiento_label: "Origine :",
        val_nacimiento: "Mexico",
        lbl_nacionalidad_label: "Nationalité :",
        val_nacionalidad: "Mexicaine",
        lbl_estatura_label: "Style :",
        val_estatura: "Rock & Roll / Classiques / Reprises",
        lbl_formacion_titulo: "Parcours Artistique",
        lbl_perfil_label: "Profil :",
        val_perfil_text: "Musicien de rue et indépendant à haute performance scénique.",
        lbl_desempeno_label: "Compétence :",
        val_desempeno_text: "Coordination simultanée de plusieurs instruments et percussions en direct.",
        lbl_especialidad_titulo: "Spécialité",
        lbl_disciplina_label: "Instrumentation :",
        val_disciplina_text: "Exécution simultanée de guitare, batterie, harmonica et accessoires en même temps.",
        lbl_tecnica_label: "Proposition :",
        val_tecnica_text: "Sauvetage du rock classique, pop et genres rétro avec des arrangements acoustiques et percussifs autogérés.",
        lbl_logros_titulo: "Réalisations et Parcours",
        val_logro_1: "📌 Phénomène viral sur les réseaux sociaux et dans les espaces publics emblématiques de Mexico (comme le Parque México à Condesa).",
        val_logro_2: "🎸 Interprète exceptionnel capable de maîtriser plusieurs instruments simultanément devant des centaines de spectateurs.",
        val_logro_3: "🌐 Solide carrière indépendante portant la musique urbaine et le rock de rue vers de grandes scènes et plateformes numériques.",
        btn_regresar_menu: "RETOOUR AU MENU 🚀",
        btn_conoceme: "À PROPOS",
        btn_portafolio: "PORTFOLIO D'IMAGES",
        btn_poder_musica: "LE POUVOIR DE LA MUSIQUE",
        btn_contacto: "CONTACT",
        contact_title: "RÉSEAUX SOCIAUX",
        contact_contracting: "BOOKING 52 56 5482 8000",
        btn_whatsapp: "WHATSAPP",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_youtube: "YOUTUBE",
        qr_heading: "SCANNEZ LE CODE QR",
        btn_share_qr: "PARTAGER LE QR",
        meta_title: "Tonah L'Homme Orchestre",
        cat1_t: "BIOGRAPHIE",
        cat1_c: "Biographie et parcours artistique de Tonah L'Homme Orchestre...",
        cat2_t: "PORTEFEUILLE D'IMAGES",
        cat2_c: "Tous les jours je répète, j'ajuste mon système de poulies et de pédales et je perfectionne chaque détail de mon spectacle...",
        cat3_t: "LE POUVOIR DE LA MUSIQUE",
        cat3_c: "Ma plus grande force est la polyvalence combinée à l'authenticité...",
        lbl_mis_fortalezas: "Le Mexique dans le cœur",
        btn_tributo_tri: "Tribut au TRI",
        btn_junto_mar: "Au bord de la mer",
        btn_con_gente: "Chanter à Paris",
        btn_cantando_beatles: "Chanter The Beatles",
        btn_video_historia: "JE ME PRÉSENTE",
        btn_ver_detalles: "VOIR LES DÉTAILS"
    },
    ko: {
        meta_title: "토나 원맨밴드",
        lbl_idioma: "언어",
        lbl_edition: "원맨밴드",
        lbl_hero_title: "토나",
        alt_hero_img: "토나 원맨밴드",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "재생하려면 클릭",
        btn_grandes_momentos: "위대한 순간들",
        modal_grandes_momentos_title: "위대한 순간들",
        modal_grandes_momentos_desc: "이미지를 터치하여 확대하고 넘겨보세요",
        btn_cerrar: "닫기",
        btn_comparte_historia: "제 이야기를 공유해 주세요. 감사합니다",
        lbl_producido_por: "\"TALENT CARD\" 제작",
        btn_contactanos_card: "문의하기",
        lbl_conoceme: "소개",
        lbl_biografia: "약력",
        lbl_nombre_label: "이름:",
        val_nombre: "토나",
        lbl_edad_label: "프로젝트:",
        val_edad: "인디 어반 뮤직",
        lbl_nacimiento_label: "출신:",
        val_nacimiento: "멕시코시티",
        lbl_nacionalidad_label: "국적:",
        val_nacionalidad: "멕시코",
        lbl_estatura_label: "스타일:",
        val_estatura: "로큰롤 / 클래식 / 커버",
        lbl_formacion_titulo: "예술적 배경",
        lbl_perfil_label: "프로필:",
        val_perfil_text: "고공연력을 지닌 독립 거리 뮤지션.",
        lbl_desempeno_label: "능력:",
        val_desempeno_text: "라이브에서 여러 악기와 타악기를 동시에 조율 및 연주.",
        lbl_especialidad_titulo: "전문 분야",
        lbl_disciplina_label: "악기 구성:",
        val_disciplina_text: "기타, 드럼, 하모니카 및 소품을 동시에 연주.",
        lbl_tecnica_label: "제안:",
        val_tecnica_text: "자체 제작한 어쿠스틱 및 타악기 편곡을 통한 클래식 록, 팝, 레트로 장르의 부활.",
        lbl_logros_titulo: "성과 및 경력",
        val_logro_1: "📌 멕시코시티의 상징적인 공공장소(콘데사의 파르케 멕시코 등)와 소셜 미디어에서의 바이럴 현상.",
        val_logro_2: "🎸 수백 명의 관객 앞에서 여러 악기를 동시에 마스터할 수 있는 뛰어난 연주자.",
        val_logro_3: "🌐 대규모 무대와 디지털 플랫폼으로 어반 음악과 거리 록을 전파하는 견고한 독립 음악가 여정.",
        btn_regresar_menu: "메뉴로 돌아가기 🚀",
        btn_conoceme: "소개",
        btn_portafolio: "이미지 포트폴리오",
        btn_poder_musica: "음악의 힘",
        btn_contacto: "연락처",
        contact_title: "소셜 미디어",
        contact_contracting: "섭외 문의 52 56 5482 8000",
        btn_whatsapp: "왓츠앱",
        btn_facebook: "페이스북",
        btn_instagram: "인스타그램",
        btn_youtube: "유튜브",
        qr_heading: "QR 코드 스캔",
        btn_share_qr: "QR 공유",
        meta_title: "토나 원맨밴드",
        cat1_t: "연대기",
        cat1_c: "토나 원맨밴드의 전기 및 예술적 여정...",
        cat2_t: "이미지 포트폴리오",
        cat2_c: "매일 연습하고, 도풀리와 페달 시스템을 조정하며 쇼의 모든 세부 사항을 완벽하게 만듭니다...",
        cat3_t: "음악의 힘",
        cat3_c: "나의 가장 큰 강점은 진정성과 결합된 다양성입니다...",
        lbl_mis_fortalezas: "마음속의 멕시코",
        btn_tributo_tri: "TRI 트리뷰트",
        btn_junto_mar: "바닷가에서",
        btn_con_gente: "파리에서 노래하기",
        btn_cantando_beatles: "비틀즈 노래 부르기",
        btn_video_historia: "나를 소개합니다",
        btn_ver_detalles: "상세정보 보기"
    },
    de: {
        meta_title: "TONAH DIE EIN-MANN-BAND",
        lbl_idioma: "SPRACHE",
        lbl_edition: "DIE EIN-MANN-BAND",
        lbl_hero_title: "TONAH",
        alt_hero_img: "Tonah Die Ein-Mann-Band",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "KLICKEN ZUM ABSPIELEN",
        btn_grandes_momentos: "GROSSE MOMENTE",
        modal_grandes_momentos_title: "GROSSE MOMENTE",
        modal_grandes_momentos_desc: "Tippe auf ein Bild zum Vergrößern und Wischen",
        btn_cerrar: "Schließen",
        btn_comparte_historia: "TEILE MEINE GESCHICHTE, ICH DANKE DIR",
        lbl_producido_por: "PRODUZIERT VON \"TALENT CARD\"",
        btn_contactanos_card: "KONTAKTIERE UNS",
        lbl_conoceme: "ÜBER MICH",
        lbl_biografia: "Biografie",
        lbl_nombre_label: "Name:",
        val_nombre: "Tonah",
        lbl_edad_label: "Projekt:",
        val_edad: "Unabhängige Urban-Musik",
        lbl_nacimiento_label: "Herkunft:",
        val_nacimiento: "Mexiko-Stadt",
        lbl_nacionalidad_label: "Nationalität:",
        val_nacionalidad: "Mexikanisch",
        lbl_estatura_label: "Stil:",
        val_estatura: "Rock & Roll / Klassiker / Cover",
        lbl_formacion_titulo: "Künstlerischer Werdegang",
        lbl_perfil_label: "Profil:",
        val_perfil_text: "Straßen- und unabhängiger Musiker mit hoher Bühnenleistung.",
        lbl_desempeno_label: "Fähigkeit:",
        val_desempeno_text: "Gleichzeitige Live-Koordination mehrerer Instrumente und Perkussionen.",
        lbl_especialidad_titulo: "Spezialität",
        lbl_disciplina_label: "Instrumentierung:",
        val_disciplina_text: "Gleichzeitiges Spielen von Gitarre, Schlagzeug, Mundharmonika und Zubehör.",
        lbl_tecnica_label: "Konzept:",
        val_tecnica_text: "Wiederbelebung von Classic Rock, Pop und Retro-Genres mit selbstverwalteten Akustik- und Perkussionsarrangements.",
        lbl_logros_titulo: "Erfolge und Werdegang",
        val_logro_1: "📌 Virales Phänomen in sozialen Medien und an emblematischen öffentlichen Orten in CDMX (wie dem Parque México in Condesa).",
        val_logro_2: "🎸 Herausragender Interpret, der in der Lage ist, mehrere Instrumente gleichzeitig vor Hunderten von Zuschauern zu beherrschen.",
        val_logro_3: "🌐 Solide unabhängige Karriere, die urbane Musik und Straßenrock auf große Bühnen und digitale Plattformen bringt.",
        btn_regresar_menu: "ZURÜCK ZUM MENÜ 🚀",
        btn_conoceme: "ÜBER MICH",
        btn_portafolio: "BILDER-PORTFOLIO",
        btn_poder_musica: "DIE KRAFT DER MUSIK",
        btn_contacto: "KONTAKT",
        contact_title: "SOZIALE MEDIEN",
        contact_contracting: "BUCHUNGEN 52 56 5482 8000",
        btn_whatsapp: "WHATSAPP",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_youtube: "YOUTUBE",
        qr_heading: "QR-CODE SCANNEN",
        btn_share_qr: "QR TEILEN",
        meta_title: "Tonah Die One-Man-Band",
        cat1_t: "BIOGRAFIE",
        cat1_c: "Biografie und künstlerischer Werdegang von Tonah Die One-Man-Band...",
        cat2_t: "BILDERPORTFOLIO",
        cat2_c: "Jeden Tag probe ich, passe mein Flaschenzug- und Pedalsystem an und perfektioniere jedes Detail meiner Show...",
        cat3_t: "DIE MACHT DER MUSIK",
        cat3_c: "Meine größte Stärke ist die Vielseitigkeit kombiniert mit Authentizität...",
        lbl_mis_fortalezas: "Mexiko im Herzen",
        btn_tributo_tri: "Tribut an TRI",
        btn_junto_mar: "Am Meer",
        btn_con_gente: "Singend in Paris",
        btn_cantando_beatles: "The Beatles singen",
        btn_video_historia: "ICH STELLE MICH VOR",
        btn_ver_detalles: "DETAILS ANSEHEN"
    },
    ja: {
        meta_title: "トナ ワンマンバンド",
        lbl_idioma: "言語",
        lbl_edition: "ワンマンバンド",
        lbl_hero_title: "TONAH",
        alt_hero_img: "トナ ワンマンバンド",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "クリックして再生",
        btn_grandes_momentos: "名場面",
        modal_grandes_momentos_title: "名場面",
        modal_grandes_momentos_desc: "画像をタップして拡大・スワイプします",
        btn_cerrar: "閉じる",
        btn_comparte_historia: "私のストーリーをシェアしてください。感謝します",
        lbl_producido_por: "制作: \"TALENT CARD\"",
        btn_contactanos_card: "お問い合わせ",
        lbl_conoceme: "プロフィール",
        lbl_biografia: "経歴",
        lbl_nombre_label: "名前:",
        val_nombre: "トナ",
        lbl_edad_label: "プロジェクト:",
        val_edad: "インディーズ・アーバンミュージック",
        lbl_nacimiento_label: "出身:",
        val_nacimiento: "メキシコシティ",
        lbl_nacionalidad_label: "国籍:",
        val_nacionalidad: "メキシコ",
        lbl_estatura_label: "スタイル:",
        val_estatura: "ロックンロール / クラシック / カバー",
        lbl_formacion_titulo: "芸術的背景",
        lbl_perfil_label: "プロフィール:",
        val_perfil_text: "高いパフォーマンスを誇るストリートおよびインディーズミュージシャン。",
        lbl_desempeno_label: "スキル:",
        val_desempeno_text: "ライブでの複数の楽器とパーカッションの同時演奏とコーディネーション。",
        lbl_especialidad_titulo: "専門分野",
        lbl_disciplina_label: "楽器構成:",
        val_disciplina_text: "ギター、ドラム、ハーモニカ、アクセサリを同時に演奏。",
        lbl_tecnica_label: "提案:",
        val_tecnica_text: "自己管理によるアコースティックおよびパーカッションアレンジでクラシックロック、ポップ、レトロジャンルを復活。",
        lbl_logros_titulo: "実績と軌跡",
        val_logro_1: "📌 メキシコシティの象徴的な公共スペース（コンデサのパルケ・メキシコなど）やSNSでのバイラル現象。",
        val_logro_2: "🎸 何百人もの観客の前で複数の楽器を同時に演奏できる優れたパフォーマー。",
        val_logro_3: "🌐 アーバンミュージックとストリートロックを大規模なステージやデジタルプラットフォームに届ける堅実なインディーズのキャリア。",
        btn_regresar_menu: "メニューに戻る 🚀",
        btn_conoceme: "プロフィール",
        btn_portafolio: "画像ポートフォリオ",
        btn_poder_musica: "音楽の力",
        btn_contacto: "連絡先",
        contact_title: "ソーシャルメディア",
        contact_contracting: "出演依頼 52 56 5482 8000",
        btn_whatsapp: "WHATSAPP",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_youtube: "YOUTUBE",
        qr_heading: "QRコードをスキャン",
        btn_share_qr: "QRをシェア",
        meta_title: "トナ・ワンマンバンド",
        cat1_t: "伝記",
        cat1_c: "トナ・ワンマンバンドの伝記と芸術的軌跡...",
        cat2_t: "画像ポートフォリオ",
        cat2_c: "毎日リハーサルをし、プーリーとペダルのシステムを調整し、ショーの細部まで完璧に仕上げています...",
        cat3_t: "音楽の力",
        cat3_c: "私の最大の強みは、本物らしさと結びついた汎用性です...",
        lbl_mis_fortalezas: "心の中のメキシコ",
        btn_tributo_tri: "TRI トリビュート",
        btn_junto_mar: "海辺にて",
        btn_con_gente: "パリで歌う",
        btn_cantando_beatles: "ビートルズを歌う",
        btn_video_historia: "自己紹介",
        btn_ver_detalles: "詳細を見る"
    },
    zh: {
        meta_title: "托纳 一人乐队",
        lbl_idioma: "语言",
        lbl_edition: "一人乐队",
        lbl_hero_title: "TONAH",
        alt_hero_img: "托纳 一人乐队",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "点击播放",
        btn_grandes_momentos: "精彩瞬间",
        modal_grandes_momentos_title: "精彩瞬间",
        modal_grandes_momentos_desc: "点击图片放大并滑动浏览",
        btn_cerrar: "关闭",
        btn_comparte_historia: "分享我的故事，感谢您的支持",
        lbl_producido_por: "由 \"TALENT CARD\" 制作",
        btn_contactanos_card: "联系我们",
        lbl_conoceme: "关于我",
        lbl_biografia: "传记",
        lbl_nombre_label: "姓名：",
        val_nombre: "托纳",
        lbl_edad_label: "项目：",
        val_edad: "独立城市音乐",
        lbl_nacimiento_label: "产地：",
        val_nacimiento: "墨西哥城",
        lbl_nacionalidad_label: "国籍：",
        val_nacionalidad: "墨西哥",
        lbl_estatura_label: "风格：",
        val_estatura: "摇滚乐 / 经典 / 翻唱",
        lbl_formacion_titulo: "艺术背景",
        lbl_perfil_label: "简介：",
        val_perfil_text: "具有高水平演艺表现的街头独立音乐人。",
        lbl_desempeno_label: "技能：",
        val_desempeno_text: "现场同时协调演奏多种乐器与打击乐。",
        lbl_especialidad_titulo: "专长",
        lbl_disciplina_label: "乐器配置：",
        val_disciplina_text: "同时演奏吉他、架子鼓、口琴及配件。",
        lbl_tecnica_label: "理念：",
        val_tecnica_text: "通过自主管理的声学与打击乐编曲复兴经典摇滚、流行及复古流派。",
        lbl_logros_titulo: "成就与经历",
        val_logro_1: "📌 在社交媒体及墨西哥城标志性公共空间（如孔德asa的墨西哥公园）引起轰动的病毒式现象。",
        val_logro_2: "🎸 能够在数百名观众面前同时驾驭多种乐器的杰出表演者。",
        val_logro_3: "🌐 坚实的独立音乐生涯，将城市音乐和街头摇滚带上各大舞台与数字平台。",
        btn_regresar_menu: "返回菜单 🚀",
        btn_conoceme: "关于我",
        btn_portafolio: "图片作品集",
        btn_poder_musica: "音乐的力量",
        btn_contacto: "联系方式",
        contact_title: "社交媒体",
        contact_contracting: "演出预订 52 56 5482 8000",
        btn_whatsapp: "WHATSAPP",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_youtube: "YOUTUBE",
        qr_heading: "扫描二维码",
        btn_share_qr: "分享二维码",
        meta_title: "托纳一人乐队",
        cat1_t: "传记",
        cat1_c: "托纳一人乐队的传记与艺术生涯...",
        cat2_t: "图片作品集",
        cat2_c: "我每天排练，调整我的滑轮和踏板系统，并完善我演出的每一个细节...",
        cat3_t: "音乐的力量",
        cat3_c: "我最大的优势是多才多艺与真实性的结合...",
        lbl_mis_fortalezas: "墨西哥在心中",
        btn_tributo_tri: "致敬 TRI",
        btn_junto_mar: "海滨",
        btn_con_gente: "在巴黎歌唱",
        btn_cantando_beatles: "演唱披头士",
        btn_video_historia: "自我介绍",
        btn_ver_detalles: "查看详情"
    }
};

function changeLanguage(lang) {
    localStorage.setItem('selectedLanguage', lang);

    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    const altElements = document.querySelectorAll('[data-i18n-alt]');
    altElements.forEach(el => {
        const key = el.getAttribute('data-i18n-alt');
        if (translations[lang] && translations[lang][key]) {
            el.setAttribute('alt', translations[lang][key]);
        }
    });

    if (translations[lang] && translations[lang]['meta_title']) {
        document.title = translations[lang]['meta_title'];
    }

    document.querySelectorAll('.lang-chip').forEach(chip => {
        chip.classList.remove('active');
        if (chip.getAttribute('onclick').includes(`'${lang}'`)) {
            chip.classList.add('active');
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLanguage') || 'es';
    changeLanguage(savedLang);
});