const translations = {
    es: {
        meta_title: "TONAH | EL HOMBRE ORQUESTA",
        lbl_idioma: "IDIOMA",
        alt_hero_img: "Tonah El Hombre Orquesta",
        lbl_edition: "EL HOMBRE ORQUESTA",
        lbl_hero_title: "TONAH",
        btn_conoceme: "CONOCEME",
        btn_portafolio: "PORTAFOLIO DE IMAGENES",
        btn_poder_musica: "EL PODER DE LA MUSICA",
        btn_contacto: "CONTACTO",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "CLIC PARA REPRODUCIR",
        btn_grandes_momentos: "GRANDES MOMENTOS",
        modal_grandes_momentos_title: "GRANDES MOMENTOS",
        modal_grandes_momentos_desc: "Toca una imagen para ampliarla y deslizarla",
        btn_cerrar: "Cerrar",
        btn_comparte_historia: "COMPARTE MI HISTORIA TE LO AGRADEZCO",
        lbl_producido_por: 'PRODUCIDO POR "TALENT CARD"',
        btn_contactanos_card: "CONTÁCTANOS",
        cat2_t: "PORTAFOLIO DE IMAGENES",
        cat2_c: "Todos los días ensayo, ajusto mi sistema de poleas y pedales y perfecciono cada detalle de mi show. Llevo una vida artística muy intensa en las calles y recintos, pero trabajo muy duro y con absoluta disciplina por mi gran pasión: la música en vivo y el arte de ser un hombre orquesta. Sé que el camino de la escena independiente es exigente, por lo que tengo claro que, además de la improvisación, me preparo con profesionalismo y entrega total para conectar con el público.",
        cat3_t: "EL PODER DE LA MUSICA",
        cat3_c: "Mi mayor fortaleza es la versatilidad combinada con la autenticidad y el impacto de ejecutar múltiples instrumentos al mismo tiempo. Fuera y dentro de las calles, mantengo la creatividad, el rigor en mi sistema artesanal y el compromiso absoluto con cada presentación. Trabajo frente al público con carisma, presencia escénica y una constante búsqueda de innovación musical.",
        lbl_mis_fortalezas: "Mis Fortalezas en Video",
        btn_tributo_tri: "Tributo al TRI",
        btn_junto_mar: "Junto al Mar",
        btn_con_gente: "Con mi gente",
        btn_cantando_beatles: "Cantando a The beatles",
        btn_video_historia: "VIDEO DE MI HISTORIA",
        // Nuevas claves del perfil
        lbl_nombre_label: "Nombre:",
        val_nombre: "Tonatiuh Zamarrón",
        lbl_edad_label: "Edad:",
        val_edad: "26 años",
        lbl_nacimiento_label: "Nacimiento:",
        val_nacimiento: "15 Nov / CDMX",
        lbl_nacionalidad_label: "Nacionalidad:",
        val_nacionalidad: "Mexicana",
        lbl_estatura_label: "Estatura / Peso:",
        val_estatura: "1.75 m / 70 kg",
        lbl_formacion_titulo: "Formación Artística",
        lbl_perfil_label: "Perfil:",
        val_perfil_text: "Músico Independiente, Autodidacta y Compositor.",
        lbl_desempeno_label: "Desempeño:",
        val_desempeno_text: "100% Dominio motriz, ejecución simultánea y conexión urbana.",
        lbl_especialidad_titulo: "Especialidad",
        lbl_disciplina_label: "Disciplina:",
        val_disciplina_text: "Músico Callejero / Show en Vivo.",
        lbl_tecnica_label: "Técnica:",
        val_tecnica_text: "Independencia corporal extrema (bombo, charles, guitarra y armónicas con sistema artesanal de poleas y pedales).",
        lbl_logros_titulo: "Logros y Trayectoria",
        val_logro_1: "📌 Artista urbano referente en el emblemático Parque México (Condesa, CDMX).",
        val_logro_2: "🎸 Invitado especial de Álex Lora para tocar con El Tri en la Arena Ciudad de México (\"Chavo de onda\").",
        val_logro_3: "🌐 Proyección viral masiva en redes y reconocimiento de figuras globales como Paul McCartney."
    },
    en: {
        meta_title: "TONAH | THE ONE-MAN BAND",
        lbl_idioma: "LANGUAGE",
        alt_hero_img: "Tonah The One-Man Band",
        lbl_edition: "THE ONE-MAN BAND",
        lbl_hero_title: "TONAH",
        btn_conoceme: "ABOUT ME",
        btn_portafolio: "IMAGE PORTFOLIO",
        btn_poder_musica: "THE POWER OF MUSIC",
        btn_contacto: "CONTACT",
        alt_video_thumb: "Tonah Video Preview",
        lbl_clic_reproducir: "CLICK TO PLAY",
        btn_grandes_momentos: "GREAT MOMENTS",
        modal_grandes_momentos_title: "GREAT MOMENTS",
        modal_grandes_momentos_desc: "Tap an image to zoom and swipe",
        btn_cerrar: "Close",
        btn_comparte_historia: "SHARE MY STORY, I REALLY APPRECIATE IT",
        lbl_producido_por: 'PRODUCED BY "TALENT CARD"',
        btn_contactanos_card: "CONTACT US",
        cat2_t: "IMAGE PORTFOLIO",
        cat2_c: "Every day I rehearse, adjust my pulley and pedal system, and perfect every detail of my show. I lead a very intense artistic life in the streets and venues, but I work very hard and with absolute discipline for my great passion: live music and the art of being a one-man band. I know the path of the independent scene is demanding, so I am clear that, in addition to improvisation, I prepare myself with professionalism and total dedication to connect with the audience.",
        cat3_t: "THE POWER OF MUSIC",
        cat3_c: "My greatest strength is versatility combined with authenticity and the impact of playing multiple instruments at the same time. Inside and outside the streets, I maintain creativity, rigor in my artisanal system, and an absolute commitment to each performance. I work in front of the audience with charisma, stage presence, and a constant pursuit of musical innovation.",
        lbl_mis_fortalezas: "My Strengths on Video",
        btn_tributo_tri: "Tribute to El TRI",
        btn_junto_mar: "By the Sea",
        btn_con_gente: "With My People",
        btn_cantando_beatles: "Singing The Beatles",
        btn_video_historia: "VIDEO OF MY STORY",
        // Nuevas claves del perfil
        lbl_nombre_label: "Name:",
        val_nombre: "Tonatiuh Zamarrón",
        lbl_edad_label: "Age:",
        val_edad: "26 years old",
        lbl_nacimiento_label: "Birth:",
        val_nacimiento: "Nov 15 / CDMX",
        lbl_nacionalidad_label: "Nationality:",
        val_nacionalidad: "Mexican",
        lbl_estatura_label: "Height / Weight:",
        val_estatura: "1.75 m / 70 kg",
        lbl_formacion_titulo: "Artistic Background",
        lbl_perfil_label: "Profile:",
        val_perfil_text: "Independent Musician, Self-taught and Composer.",
        lbl_desempeno_label: "Performance:",
        val_desempeno_text: "100% Motor control, simultaneous execution, and urban connection.",
        lbl_especialidad_titulo: "Specialty",
        lbl_disciplina_label: "Discipline:",
        val_disciplina_text: "Street Musician / Live Show.",
        lbl_tecnica_label: "Technique:",
        val_tecnica_text: "Extreme bodily independence (bass drum, hi-hat, guitar, and harmonicas with a custom pulley and pedal system).",
        lbl_logros_titulo: "Achievements & Track Record",
        val_logro_1: "📌 Reference urban artist in the emblematic Parque México (Condesa, CDMX).",
        val_logro_2: "🎸 Special guest of Álex Lora to play with El Tri at the Mexico City Arena (\"Chavo de onda\").",
        val_logro_3: "🌐 Massive viral reach on social media and recognition from global figures like Paul McCartney."
    },
    pt: {
        meta_title: "TONAH | O HOMEM BANDA",
        lbl_idioma: "IDIOMA",
        alt_hero_img: "Tonah O Homem Banda",
        lbl_edition: "O HOMEM BANDA",
        lbl_hero_title: "TONAH",
        btn_conoceme: "CONHECE-ME",
        btn_portafolio: "PORTFÓLIO DE IMAGENS",
        btn_poder_musica: "O PODER DA MÚSICA",
        btn_contacto: "CONTATO",
        alt_video_thumb: "Tonah Prévia de Vídeo",
        lbl_clic_reproducir: "CLIQUE PARA REPRODUZIR",
        btn_grandes_momentos: "GRANDES MOMENTOS",
        modal_grandes_momentos_title: "GRANDES MOMENTOS",
        modal_grandes_momentos_desc: "Toque em uma imagem para ampliar e deslizar",
        btn_cerrar: "Fechar",
        btn_comparte_historia: "COMPARTILHE MINHA HISTÓRIA, EU AGRADEÇO MUITO",
        lbl_producido_por: 'PRODUZIDO POR "TALENT CARD"',
        btn_contactanos_card: "CONTATO",
        cat2_t: "PORTFÓLIO DE IMAGENS",
        cat2_c: "Todos os dias ensaio, ajusto meu sistema de polias e pedales e aperfeiçoo cada detalhe do meu show. Levo uma vida artística muito intensa nas ruas e recintos, mas trabalho muito duro e com disciplina absoluta pela minha grande paixão: a música ao vivo e a arte de ser um homem banda. Sei que o caminho da cena independente é exigente, por isso tenho claro que, além da improvisação, me preparo com profissionalismo e entrega total para me conectar com o público.",
        cat3_t: "O PODER DA MÚSICA",
        cat3_c: "Minha maior força é a versatilidade combinada com a autenticidade e o impacto de tocar múltiplos instrumentos ao mesmo tempo. Fora e dentro das ruas, mantenho a criatividade, o rigor em meu sistema artesanal e o compromisso absoluto com cada apresentação. Trabalho diante do público com carisma, presença de palco e uma busca constante por inovação musical.",
        lbl_mis_fortalezas: "Minhas Forças em Vídeo",
        btn_tributo_tri: "Tributo ao El TRI",
        btn_junto_mar: "Junto ao Mar",
        btn_con_gente: "Com Minha Gente",
        btn_cantando_beatles: "Cantando The Beatles",
        btn_video_historia: "VÍDEO DA MINHA HISTÓRIA",
        // Nuevas claves del perfil
        lbl_nombre_label: "Nome:",
        val_nombre: "Tonatiuh Zamarrón",
        lbl_edad_label: "Idade:",
        val_edad: "26 anos",
        lbl_nacimiento_label: "Nascimento:",
        val_nacimiento: "15 Nov / CDMX",
        lbl_nacionalidad_label: "Nacionalidade:",
        val_nacionalidad: "Mexicana",
        lbl_estatura_label: "Altura / Peso:",
        val_estatura: "1,75 m / 70 kg",
        lbl_formacion_titulo: "Formação Artística",
        lbl_perfil_label: "Perfil:",
        val_perfil_text: "Músico Independente, Autodidata e Compositor.",
        lbl_desempeno_label: "Desempenho:",
        val_desempeno_text: "100% Domínio motor, execução simultânea e conexão urbana.",
        lbl_especialidad_titulo: "Especialidade",
        lbl_disciplina_label: "Disciplina:",
        val_disciplina_text: "Músico de Rua / Show ao Vivo.",
        lbl_tecnica_label: "Técnica:",
        val_tecnica_text: "Independência corporal extrema (bumbo, chimbal, guitarra e gaitas com sistema artesanal de polias e pedais).",
        lbl_logros_titulo: "Conquistas e Trajetória",
        val_logro_1: "📌 Artista urbano de referência no emblemático Parque México (Condesa, CDMX).",
        val_logro_2: "🎸 Convidado especial de Álex Lora para tocar com El Tri na Arena Cidade do México (\"Chavo de onda\").",
        val_logro_3: "🌐 Projeção viral massiva nas redes e reconhecimento de figuras globais como Paul McCartney."
    },
    fr: {
        meta_title: "TONAH | L'HOMME-ORCHESTRE",
        lbl_idioma: "LANGUE",
        alt_hero_img: "Tonah L'Homme-Orchestre",
        lbl_edition: "L'HOMME-ORCHESTRE",
        lbl_hero_title: "TONAH",
        btn_conoceme: "À PROPOS",
        btn_portafolio: "PORTEFEUILLE D'IMAGES",
        btn_poder_musica: "LE POUVOIR DE LA MUSIQUE",
        btn_contacto: "CONTACT",
        alt_video_thumb: "Tonah Aperçu Vidéo",
        lbl_clic_reproducir: "CLIQUEZ POUR LIRE",
        btn_grandes_momentos: "GRANDS MOMENTS",
        modal_grandes_momentos_title: "GRANDS MOMENTS",
        modal_grandes_momentos_desc: "Touchez une image pour l'agrandir et la faire glisser",
        btn_cerrar: "Fermer",
        btn_comparte_historia: "PARTAGEZ MON HISTOIRE, JE VOUS REMERCIE",
        lbl_producido_por: 'PRODUIT PAR "TALENT CARD"',
        btn_contactanos_card: "CONTACTEZ-NOUS",
        cat2_t: "PORTEFEUILLE D'IMAGES",
        cat2_c: "Chaque jour, je répète, j'ajuste mon système de poulies et de pédales et je perfectionne chaque détail de mon spectacle. Je mène une vie artistique très intense dans les rues et les salles, mais je travaille très dur et avec une discipline absolue pour ma grande passion : la musique live et l'art d'être un homme-orchestre. Je sais que le chemin de la scène indépendante est exigeant, c'est pourquoi je suis conscient qu'en plus de l'improvisation, je me prépare avec professionnalisme et dévouement total pour me connecter au public.",
        cat3_t: "LE POUVOIR DE LA MUSIQUE",
        cat3_c: "Ma plus grande force est la polyvalence combinée à l'authenticité et à l'impact de jouer de plusieurs instruments en même temps. À l'extérieur et à l'intérieur des rues, je maintiens la créativité, la rigueur de mon système artisanal et un engagement absolu envers chaque prestation. Je travaille devant le public avec charisme, présence sur scène et une recherche constante d'innovation musicale.",
        lbl_mis_fortalezas: "Mes Forces en Vidéo",
        btn_tributo_tri: "Tribut à El TRI",
        btn_junto_mar: "Au Bord de la Mer",
        btn_con_gente: "Avec Mon Peuple",
        btn_cantando_beatles: "Chantant The Beatles",
        btn_video_historia: "VIDÉO DE MON HISTOIRE",
        // Nuevas claves del perfil
        lbl_nombre_label: "Nom:",
        val_nombre: "Tonatiuh Zamarrón",
        lbl_edad_label: "Âge:",
        val_edad: "26 ans",
        lbl_nacimiento_label: "Naissance:",
        val_nacimiento: "15 Nov / CDMX",
        lbl_nacionalidad_label: "Nationalité:",
        val_nacionalidad: "Mexicaine",
        lbl_estatura_label: "Taille / Poids:",
        val_estatura: "1,75 m / 70 kg",
        lbl_formacion_titulo: "Formation Artistique",
        lbl_perfil_label: "Profil:",
        val_perfil_text: "Musicien Indépendant, Autodidacte et Compositeur.",
        lbl_desempeno_label: "Performance:",
        val_desempeno_text: "100% Maîtrise motrice, exécution simultanée et connexion urbaine.",
        lbl_especialidad_titulo: "Spécialité",
        lbl_disciplina_label: "Discipline:",
        val_disciplina_text: "Musicien de Rue / Spectacle Live.",
        lbl_tecnica_label: "Technique:",
        val_tecnica_text: "Indépendance corporelle extrême (grosse caisse, charleston, guitare et harmonicas avec système artisanal de poulies et de pédales).",
        lbl_logros_titulo: "Réalisations et Parcours",
        val_logro_1: "📌 Artiste urbain de référence dans l'emblématique Parque México (Condesa, CDMX).",
        val_logro_2: "🎸 Invité spécial d'Álex Lora pour jouer avec El Tri à l'Arena Ciudad de México (\"Chavo de onda\").",
        val_logro_3: "🌐 Projection virale massive sur les réseaux et reconnaissance de figures mondiales telles que Paul McCartney."
    },
    ko: {
        meta_title: "TONAH | 원맨밴드",
        lbl_idioma: "언어",
        alt_hero_img: "Tonah 원맨밴드",
        lbl_edition: "원맨밴드",
        lbl_hero_title: "TONAH",
        btn_conoceme: "소개",
        btn_portafolio: "이미지 포트폴리오",
        btn_poder_musica: "음악의 힘",
        btn_contacto: "연락처",
        alt_video_thumb: "Tonah 비디오 미리보기",
        lbl_clic_reproducir: "재생하려면 클릭하세요",
        btn_grandes_momentos: "위대한 순간들",
        modal_grandes_momentos_title: "위대한 순간들",
        modal_grandes_momentos_desc: "이미지를 터치하여 확대하고 넘겨보세요",
        btn_cerrar: "닫기",
        btn_comparte_historia: "제 이야기를 공유해 주셔서 정말 감사합니다",
        lbl_producido_por: '"TALENT CARD" 제작',
        btn_contactanos_card: "문의하기",
        cat2_t: "이미지 포트폴리오",
        cat2_c: "매일 리허설을 하고, 도어와 페달 시스템을 조정하며 쇼의 모든 디테일을 다듬습니다. 거리와 공연장에서 매우 강렬한 예술적 삶을 살고 있지만, 라이브 음악과 원맨밴드의 예술이라는 저의 큰 열정을 위해 절대적인 규율을 가지고 아주 열심히 일합니다. 독립 음악 신의 길이 까다롭다는 것을 잘 알고 있기에, 즉흥 연주 외에도 관객과 소통하기 위해 프로페셔널함과 전적인 헌신으로 준비하고 있습니다.",
        cat3_t: "음악의 힘",
        cat3_c: "저의 가장 큰 장점은 다양성과 진정성, 그리고 여러 악기를 동시에 연주하는 타격감이 결합된 다재다능함입니다. 거리 안팎에서 창의력, 장인 정신의 엄격함, 그리고 모든 공연에 대한 절대적인 헌신을 유지합니다. 카리스마, 무대 매너, 끊임없는 음악적 혁신 추구로 관객 앞에 섭니다.",
        lbl_mis_fortalezas: "비디오로 보는 나의 강점",
        btn_tributo_tri: "El TRI 헌정",
        btn_junto_mar: "바닷가에서",
        btn_con_gente: "나의 사람들과 함께",
        btn_cantando_beatles: "비틀즈 노래하기",
        btn_video_historia: "내 이야기 비디오",
        // Nuevas claves del perfil
        lbl_nombre_label: "이름:",
        val_nombre: "토나티우 사마론 (Tonatiuh Zamarrón)",
        lbl_edad_label: "나이:",
        val_edad: "26세",
        lbl_nacimiento_label: "생년월일:",
        val_nacimiento: "11월 15일 / CDMX",
        lbl_nacionalidad_label: "국적:",
        val_nacionalidad: "멕시코",
        lbl_estatura_label: "키 / 체중:",
        val_estatura: "1.75 m / 70 kg",
        lbl_formacion_titulo: "예술적 배경",
        lbl_perfil_label: "프로필:",
        val_perfil_text: "독립 음악가, 독학파 및 작곡가.",
        lbl_desempeno_label: "수행 능력:",
        val_desempeno_text: "100% 신체 제어력, 동시 연주 및 도시적 교감.",
        lbl_especialidad_titulo: "전문 분야",
        lbl_disciplina_label: "장르:",
        val_disciplina_text: "거리 음악가 / 라이브 쇼.",
        lbl_tecnica_label: "기술:",
        val_tecnica_text: "극단적인 신체 독립성 (수제 도르래와 페달 시스템을 이용한 베이스 드럼, 하이햇, 기타 및 하모니카 연주).",
        lbl_logros_titulo: "주요 성과 및 경력",
        val_logro_1: "📌 상징적인 멕시코시티 꼰데사(Condesa) 멕시코 공원의 대표적인 거리 예술가.",
        val_logro_2: "🎸 알렉스 로라(Álex Lora)의 특별 초청으로 멕시코시티 아레나에서 El Tri와 함께 공연 (\"Chavo de onda\").",
        val_logro_3: "🌐 소셜 미디어를 통한 대규모 바이럴 확산 및 폴 매카트니와 같은 세계적인 거장들의 인정."
    },
    de: {
        meta_title: "TONAH | DIE EIN-MANN-BAND",
        lbl_idioma: "SPRACHE",
        alt_hero_img: "Tonah Die Ein-Mann-Band",
        lbl_edition: "DIE EIN-MANN-BAND",
        lbl_hero_title: "TONAH",
        btn_conoceme: "ÜBER MICH",
        btn_portafolio: "BILDERGALERIE",
        btn_poder_musica: "DIE KRAFT DER MUSIK",
        btn_contacto: "KONTAKT",
        alt_video_thumb: "Tonah Video-Vorschau",
        lbl_clic_reproducir: "KLICKEN ZUM ABSPIELEN",
        btn_grandes_momentos: "GROSSE MOMENTE",
        modal_grandes_momentos_title: "GROSSE MOMENTE",
        modal_grandes_momentos_desc: "Tippen Sie auf ein Bild, um es zu zoomen und zu wischen",
        btn_cerrar: "Schließen",
        btn_comparte_historia: "TEILEN SIE MEINE GESCHICHTE, ICH DANKE IHNEN",
        lbl_producido_por: 'PRODUZIERT VON "TALENT CARD"',
        btn_contactanos_card: "KONTAKT",
        cat2_t: "BILDERGALERIE",
        cat2_c: "Jeden Tag probe ich, passe mein Flaschenzug- und Pedalsystem an und perfektioniere jedes Detail meiner Show. Ich lebe ein sehr intensives künstlerisches Leben auf den Straßen und in Veranstaltungsorten, aber ich arbeite sehr hart und mit absoluter Disziplin für meine große Leidenschaft: Live-Musik und die Kunst, eine Ein-Mann-Band zu sein. Ich weiß, dass der Weg der unabhängigen Szene anspruchsvoll ist, deshalb ist mir klar, dass ich mich neben der Improvisation mit Professionalität und totalem Einsatz vorbereite, um eine Verbindung zum Publikum herzustellen.",
        cat3_t: "DIE KRAFT DER MUSIK",
        cat3_c: "Meine größte Stärke ist die Vielseitigkeit, kombiniert mit Authentizität und der Wirkung, mehrere Instrumente gleichzeitig zu spielen. Innerhalb und außerhalb der Straßen bewahre ich Kreativität, die Strenge meines handwerklichen Systems und ein absolutes Engagement für jeden Auftritt. Ich arbeite vor dem Publikum mit Charisma, Bühnenpräsenz und einem ständigen Streben nach musikalischer Innovation.",
        lbl_mis_fortalezas: "Meine Stärken im Video",
        btn_tributo_tri: "Tribut an El TRI",
        btn_junto_mar: "Am Meer",
        btn_con_gente: "Mit Meinen Leuten",
        btn_cantando_beatles: "The Beatles singen",
        btn_video_historia: "VIDEO MEINER GESCHICHTE",
        // Nuevas claves del perfil
        lbl_nombre_label: "Name:",
        val_nombre: "Tonatiuh Zamarrón",
        lbl_edad_label: "Alter:",
        val_edad: "26 Jahre",
        lbl_nacimiento_label: "Geburtstag:",
        val_nacimiento: "15. Nov / CDMX",
        lbl_nacionalidad_label: "Nationalität:",
        val_nacionalidad: "Mexikanisch",
        lbl_estatura_label: "Größe / Gewicht:",
        val_estatura: "1,75 m / 70 kg",
        lbl_formacion_titulo: "Künstlerischer Werdegang",
        lbl_perfil_label: "Profil:",
        val_perfil_text: "Unabhängiger Musiker, Autodidakt und Komponist.",
        lbl_desempeno_label: "Performance:",
        val_desempeno_text: "100% Körperliche Koordination, gleichzeitige Ausführung und urbane Verbindung.",
        lbl_especialidad_titulo: "Spezialität",
        lbl_disciplina_label: "Disziplin:",
        val_disciplina_text: "Straßenmusiker / Live-Show.",
        lbl_tecnica_label: "Technik:",
        val_tecnica_text: "Extreme Körperunabhängigkeit (Bassdrum, Hi-Hat, Gitarre und Mundharmonikas mit handgefertigtem Flaschenzug- und Pedalsystem).",
        lbl_logros_titulo: "Erfolge und Meilensteine",
        val_logro_1: "📌 Bekannter Straßenkünstler im emblematischen Parque México (Condesa, CDMX).",
        val_logro_2: "🎸 Spezieller Gast von Álex Lora, um mit El Tri in der Arena Ciudad de México zu spielen („Chavo de onda“).",
        val_logro_3: "🌐 Massive virale Reichweite in sozialen Netzwerken und Anerkennung durch globale Größen wie Paul McCartney."
    },
    ja: {
        meta_title: "TONAH | 一人バンド",
        lbl_idioma: "言語",
        alt_hero_img: "Tonah 一人バンド",
        lbl_edition: "一人バンド",
        lbl_hero_title: "TONAH",
        btn_conoceme: "私について",
        btn_portafolio: "画像ポートフォリオ",
        btn_poder_musica: "音楽の力",
        btn_contacto: "お問い合わせ",
        alt_video_thumb: "Tonah ビデオプレビュー",
        lbl_clic_reproducir: "クリックして再生",
        btn_grandes_momentos: "素晴らしい瞬間",
        modal_grandes_momentos_title: "素晴らしい瞬間",
        modal_grandes_momentos_desc: "画像をタップして拡大・スワイプします",
        btn_cerrar: "閉じる",
        btn_comparte_historia: "私の話をシェアしていただきありがとうございます",
        lbl_producido_por: '"TALENT CARD" 製',
        btn_contactanos_card: "お問い合わせ",
        cat2_t: "画像ポートフォリオ",
        cat2_c: "毎日リハーサルを行い、プーリーとペダルのシステムを調整し、ショーの細部まで磨き上げています。路上や会場で非常に濃密なアーティスト生活を送っていますが、ライブ音楽と一人バンドという私の大きな情熱のために、徹底した規律を持って懸命に働いています。インディーズの道が厳しいことは分かっているため、即興だけでなく、プロ意識と全身全霊の献身をもって観客とつながる準備をしています。",
        cat3_t: "音楽の力",
        cat3_c: "私の最大の強さは、多様性と本物らしさが融合し、複数の楽器を同時に演奏するインパクトです。路上でも屋内でも、創造性、手作りのシステムに対する厳格さ、そしてすべてのパフォーマンスに対する絶対的なコミットメントを維持しています。カリスマ性、ステージプレゼンス、そして絶え間ない音楽的革新の追求を持って観客の前に立ちます。",
        lbl_mis_fortalezas: "動画で見る私の強み",
        btn_tributo_tri: "El TRIへのトリビュート",
        btn_junto_mar: "海辺で",
        btn_con_gente: "私を支える人々と",
        btn_cantando_beatles: "ビートルズを歌う",
        btn_video_historia: "私のストーリーのビデオ",
        // Nuevas claves del perfil
        lbl_nombre_label: "名前:",
        val_nombre: "トナティウ・サマロン (Tonatiuh Zamarrón)",
        lbl_edad_label: "年齢:",
        val_edad: "26歳",
        lbl_nacimiento_label: "生年月日:",
        val_nacimiento: "11月15日 / メキシコシティ",
        lbl_nacionalidad_label: "国籍:",
        val_nacionalidad: "メキシコ",
        lbl_estatura_label: "身長 / 体重:",
        val_estatura: "1.75 m / 70 kg",
        lbl_formacion_titulo: "芸術的経歴",
        lbl_perfil_label: "プロフィール:",
        val_perfil_text: "インディーズミュージシャン、独学、作曲家。",
        lbl_desempeno_label: "パフォーマンス:",
        val_desempeno_text: "100%の運動制御、同時演奏、そして都市での強い一体感。",
        lbl_especialidad_titulo: "専門分野",
        lbl_disciplina_label: "ジャンル:",
        val_disciplina_text: "ストリートミュージシャン / ライブショー。",
        lbl_tecnica_label: "テクニック:",
        val_tecnica_text: "極限の身体的独立性（自作のプーリーとペダルシステムによるバスドラム、ハイハット、ギター、ハーモニカの同時演奏）。",
        lbl_logros_titulo: "実績と軌跡",
        val_logro_1: "📌 メキシコシティの象徴的な公園「パルケ・メヒコ（コンデサ）」を代表するストリートアーティスト。",
        val_logro_2: "🎸 アレックス・ロラ（Álex Lora）の特別ゲストとして、メキシコシティ・アリーナで「El TRI」と共演（「Chavo de onda」）。",
        val_logro_3: "🌐 SNSでの大規模なバイラル拡散と、ポール・McCartneyをはじめとする世界的な著名人からの称賛。"
    },
    zh: {
        meta_title: "TONAH | 独角乐队",
        lbl_idioma: "语言",
        alt_hero_img: "Tonah 独角乐队",
        lbl_edition: "独角乐队",
        lbl_hero_title: "TONAH",
        btn_conoceme: "关于我",
        btn_portafolio: "图片作品集",
        btn_poder_musica: "音乐的力量",
        btn_contacto: "联系方式",
        alt_video_thumb: "Tonah 视频预览",
        lbl_clic_reproducir: "点击播放",
        btn_grandes_momentos: "精彩瞬间",
        modal_grandes_momentos_title: "精彩瞬间",
        modal_grandes_momentos_desc: "轻触图片即可放大并滑动",
        btn_cerrar: "关闭",
        btn_comparte_historia: "分享我的故事，非常感谢您",
        lbl_producido_por: '由 "TALENT CARD" 制作',
        btn_contactanos_card: "联系我们",
        cat2_t: "图片作品集",
        cat2_c: "每天我都进行排练，调整我的滑轮和踏板系统，并完善我演出的每一个细节。我在街头和场馆里过着非常密集的艺术生活，但我以绝对的纪律和极其努力的工作来追求我的巨大热情：现场音乐以及独角乐队的艺术。我深知独立音乐道路的严苛，因此我清楚，除了即兴表演之外，我还要以专业精神和全身心的投入做好准备，以便与观众建立深厚的连接。",
        cat3_t: "音乐的力量",
        cat3_c: "我最大的优势是多才多艺，结合了真实性以及同时演奏多种乐器的震撼力。无论是在街头还是室内，我都保持着创造力、手工系统中的严谨态度以及对每一场演出的绝对承诺。我带着个人魅力、舞台表现力以及对音乐创新的不断追求在观众面前表演。",
        lbl_mis_fortalezas: "视频展示我的优势",
        btn_tributo_tri: "致敬 El TRI 乐队",
        btn_junto_mar: "海边",
        btn_con_gente: "与我的人民在一起",
        btn_cantando_beatles: "演唱披头士歌曲",
        btn_video_historia: "我的故事视频",
        // Nuevas claves del perfil
        lbl_nombre_label: "姓名:",
        val_nombre: "托纳蒂乌·萨马龙 (Tonatiuh Zamarrón)",
        lbl_edad_label: "年龄:",
        val_edad: "26岁",
        lbl_nacimiento_label: "出生日期:",
        val_nacimiento: "11月15日 / 墨西哥城",
        lbl_nacionalidad_label: "国籍:",
        val_nacionalidad: "墨西哥",
        lbl_estatura_label: "身高 / 体重:",
        val_estatura: "1.75米 / 70公斤",
        lbl_formacion_titulo: "艺术背景",
        lbl_perfil_label: "个人简介:",
        val_perfil_text: "独立音乐人、自学成才者兼词曲创作者。",
        lbl_desempeno_label: "表演特质:",
        val_desempeno_text: "100% 的身体控制力、同步演奏与城市共鸣。",
        lbl_especialidad_titulo: "专业特长",
        lbl_disciplina_label: "领域:",
        val_disciplina_text: "街头音乐人 / 现场演出。",
        lbl_tecnica_label: "技术:",
        val_tecnica_text: "极致的肢体独立性（利用定制的滑轮和踏板系统同时演奏底鼓、踩镲、吉他和口琴）。",
        lbl_logros_titulo: "成就与经历",
        val_logro_1: "📌 墨西哥城标志性孔德萨区（Condesa）墨西哥公园（Parque México）的标杆性街头艺术家。",
        val_logro_2: "🎸 应 Álex Lora 特邀，在墨西哥城竞技场与 El TRI 同台演出（“Chavo de onda”）。",
        val_logro_3: "🌐 在社交媒体上获得大规模病毒式传播，并得到保罗·麦卡特尼等全球巨星的认可。"
    }
};

function changeLanguage(lang) {
    localStorage.setItem('selectedLanguage', lang);

    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    const altElements = document.querySelectorAll('[data-i18n-alt]');
    altElements.forEach(el => {
        const key = el.getAttribute('data-i18n-alt');
        if (translations[lang] && translations[lang][key]) {
            el.setAttribute('alt', translations[lang][key]);
        }
    });

    if (translations[lang] && translations[lang]['meta_title']) {
        document.title = translations[lang]['meta_title'];
    }

    document.querySelectorAll('.lang-chip').forEach(chip => {
        chip.classList.remove('active');
        if (chip.getAttribute('onclick').includes(`'${lang}'`)) {
            chip.classList.add('active');
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLanguage') || 'es';
    changeLanguage(savedLang);
});